trigger_common: &trigger_common
  image: plugins/downstream
  fork: true
  secrets: [ downstream_token, downstream_server ]
  params:
    - FORCED_OS_VERSION=centos7


pipeline:
  docker:
    image: metwork/drone-docker-specific-image:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root:/root
    commands:
      - if test "${DRONE_BRANCH}" = "master"; then docker build -t metwork/mfext-centos7-buildimage:master -t metwork/mfext-centos7-buildimage:latest .; else docker build -t metwork/mfext-centos7-buildimage:${DRONE_BRANCH} .; fi
      - docker push metwork/mfext-centos7-buildimage:${DRONE_BRANCH}
      - if test "${DRONE_BRANCH}" = "master"; then docker push metwork/mfext-centos7-buildimage:latest; fi
    when:
      event: push
  trigger_integration:
    <<: *trigger_common
    repositories:
      - metwork-framework/mfext@integration
    when:
      status: [ success ]
      event: push
      branch: integration
  trigger_master:
    <<: *trigger_common
    repositories:
      - metwork-framework/mfext@master
    when:
      status: [ success ]
      event: push
      branch: master 
